apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend

spec:
  replicas: 3
  selector:
    matchLabels: 
      name: httpd-frontend-img
  
  template:
    metadata:
      labels:
        name: httpd-frontend-img

    spec:
      containers:
        - name: httpd-frontend
          image: httpd-frontend-img