apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp-pod
    Name: myapp-pod
    Owner: Nikhil
    Purpose: test-k8-pods

spec:
  containers:
    - name: nginx-container
      image: nginx
