apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-replica-set
  labels:
    name: new-replica-set
    Owner: NS

spec:
  replicas: 4
  selector:
    matchLabels:
      name: busybox-pod

  ### pods information
  template:
    spec:
      containers:
        - name: ns-test-replica-set-buzybox
          image: busybox
    metadata:  
      labels:
        name: busybox-pod